### ISSUE TITLE
苏神好！想询问一下AttributeError: module 'keras.engine.base_layer' has no attribute 'Node'

### ISSUE THREAD

**Issue by qihaiyuyin** [bojone/SPACES#44]
Traceback (most recent call last):
  File "E:\wp\SPACES-main\extract_vectorize.py", line 10, in <module>
    from bert4keras.models import build_transformer_model
  File "E:\python\anaconda\lib\site-packages\bert4keras\models.py", line 6, in <module>
    from bert4keras.layers import *
  File "E:\python\anaconda\lib\site-packages\bert4keras\layers.py", line 100, in <module>
    NodeBase = keras.engine.base_layer.Node
AttributeError: module 'keras.engine.base_layer' has no attribute 'Node'

是在windows环境下跑的，Keras版本是2.3.1，请问这个是哪个环节的问题……

**Comment by qihaiyuyin** [comment]
解决了，pip install下的keras库有问题……
