### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by renmengxing099128** [bojone/SPACES#8]
Traceback (most recent call last):
  File "seq2seq_convert.py", line 62, in <module>
    convert(data_seq2seq_json, data, data_x)
  File "seq2seq_convert.py", line 41, in convert
    total_results.append(fold_convert(data, data_x, fold))
  File "seq2seq_convert.py", line 16, in fold_convert
    model.load_weights('weights/extract_model.%s.weights' % fold)
  File "D:\Anaconda3\envs\python3.6\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "D:\Anaconda3\envs\python3.6\lib\site-packages\keras\engine\network.py", line 1221, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "D:\Anaconda3\envs\python3.6\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "D:\Anaconda3\envs\python3.6\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'weights/extract_model.1.weights', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

运行过程中， 出现该错误， 但是路径我检查了是对的（根据博主建议， 写的绝对路径），  这个问题在网上也没找到答案， 所以在这里咨询一下， 谢谢！

**Comment by bojone** [comment]
这很明显就是没找到权重文件的意思啊，你是不是没训练完抽取模型？看一下weights目录有没有该文件不就行了？

**Comment by renmengxing099128** [comment]
😂， 我这个训练完成了， 这里面又这个文件， 但是它自己就是找不到  不知道什么问题 😓




| |
rmx099128
|
|
rmx099128@163.com
|
签名由网易邮箱大师定制
On 1/20/2021 11:39，苏剑林(Jianlin Su)<notifications@github.com> wrote：

这很明显就是没找到权重文件的意思啊，你是不是没训练完抽取模型？看一下weights目录有没有该文件不就行了？

**Comment by bojone** [comment]
你说 `ls weights/extract_model.1.weights` 是存在的？我不大相信～你进到当前目录下跑了没？

**Comment by renmengxing099128** [comment]
然后 训练生成的是“extract_model.0.weights”    报错说找不到“extract_model.1.weights”   当我把文件改为“extract_model.1.weights”时， 就报错找不到“extract_model.0.weights”， 很迷惑 
| |
rmx099128
|
|
rmx099128@163.com
|
签名由网易邮箱大师定制
On 1/20/2021 11:40，rmx099128<rmx099128@163.com> wrote：
😂， 我这个训练完成了， 这里面又这个文件， 但是它自己就是找不到  不知道什么问题 😓




| |
rmx099128
|
|
rmx099128@163.com
|
签名由网易邮箱大师定制
On 1/20/2021 11:39，苏剑林(Jianlin Su)<notifications@github.com> wrote：

这很明显就是没找到权重文件的意思啊，你是不是没训练完抽取模型？看一下weights目录有没有该文件不就行了？

**Comment by bojone** [comment]
> 然后 训练生成的是“extract_model.0.weights” 报错说找不到“extract_model.1.weights” 当我把文件改为“extract_model.1.weights”时， 就报错找不到“extract_model.0.weights”， 很迷惑 | | rmx099128 | | rmx099128@163.com | 签名由网易邮箱大师定制 On 1/20/2021 11:40，rmx099128<rmx099128@163.com> wrote： 😂， 我这个训练完成了， 这里面又这个文件， 但是它自己就是找不到 不知道什么问题 😓 | | rmx099128 | | rmx099128@163.com | 签名由网易邮箱大师定制 On 1/20/2021 11:39，苏剑林(Jianlin Su)<notifications@github.com> wrote： 这很明显就是没找到权重文件的意思啊，你是不是没训练完抽取模型？看一下weights目录有没有该文件不就行了？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

训练生成的是extract_model.1.weights～extract_model.14.weights，一共15个文件。

**Comment by renmengxing099128** [comment]
哦  那我知道了， 我里面只有一个权重文件， 因为我循环执行的时候   应该是文件名被覆盖了   所以只有一个  我在看看，   太感谢您， 打扰您了， 谢谢~~


| |
rmx099128
|
|
rmx099128@163.com
|
签名由网易邮箱大师定制
On 1/20/2021 11:43，苏剑林(Jianlin Su)<notifications@github.com> wrote：

然后 训练生成的是“extract_model.0.weights” 报错说找不到“extract_model.1.weights” 当我把文件改为“extract_model.1.weights”时， 就报错找不到“extract_model.0.weights”， 很迷惑 | | rmx099128 | | rmx099128@163.com | 签名由网易邮箱大师定制 On 1/20/2021 11:40，rmx099128rmx099128@163.com wrote： 😂， 我这个训练完成了， 这里面又这个文件， 但是它自己就是找不到 不知道什么问题 😓 | | rmx099128 | | rmx099128@163.com | 签名由网易邮箱大师定制 On 1/20/2021 11:39，苏剑林(Jianlin Su)notifications@github.com wrote： 这很明显就是没找到权重文件的意思啊，你是不是没训练完抽取模型？看一下weights目录有没有该文件不就行了？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

训练生成的是extract_model.1.weights～extract_model.14.weights，一共15个文件。

**Comment by bojone** [comment]
> 哦 那我知道了， 我里面只有一个权重文件， 因为我循环执行的时候 应该是文件名被覆盖了 所以只有一个 我在看看， 太感谢您， 打扰您了， 谢谢~~ | | rmx099128 | | rmx099128@163.com | 签名由网易邮箱大师定制 On 1/20/2021 11:43，苏剑林(Jianlin Su)<notifications@github.com> wrote： 然后 训练生成的是“extract_model.0.weights” 报错说找不到“extract_model.1.weights” 当我把文件改为“extract_model.1.weights”时， 就报错找不到“extract_model.0.weights”， 很迷惑 | | rmx099128 | | rmx099128@163.com | 签名由网易邮箱大师定制 On 1/20/2021 11:40，rmx099128rmx099128@163.com wrote： 😂， 我这个训练完成了， 这里面又这个文件， 但是它自己就是找不到 不知道什么问题 😓 | | rmx099128 | | rmx099128@163.com | 签名由网易邮箱大师定制 On 1/20/2021 11:39，苏剑林(Jianlin Su)notifications@github.com wrote： 这很明显就是没找到权重文件的意思啊，你是不是没训练完抽取模型？看一下weights目录有没有该文件不就行了？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 训练生成的是extract_model.1.weights～extract_model.14.weights，一共15个文件。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

```shell
python extract_model.py 0
python extract_model.py 1
python extract_model.py 2
...
python extract_model.py 14
```

**Comment by renmengxing099128** [comment]
您好， 我还想请问您一个问题， windows运行有问题， 所以我重新按照git上面的要求，在Linux上部署了一套环境，然后执行shell脚本的时候有问题：（1）extract_convert报错：TypeError: Object of type 'int64' is not JSON serializable， 但是引入NumpyEncoder后，修改代码：f.write(json.dumps(d, cls=NpEncoder, ensure_ascii=False) + '\n')  该问题解决，  （2）之后重新运行， extract_model模块报错：ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)， 这个问题就是说维度不对应，在网上也找了很多方法进行解决， 但是都没解决， 如果您知道，可以给我说一下，万分感谢...


| |
rmx099128
|
|
rmx099128@163.com
|
签名由网易邮箱大师定制
On 1/20/2021 11:49，苏剑林(Jianlin Su)<notifications@github.com> wrote：

哦 那我知道了， 我里面只有一个权重文件， 因为我循环执行的时候 应该是文件名被覆盖了 所以只有一个 我在看看， 太感谢您， 打扰您了， 谢谢~~ | | rmx099128 | | rmx099128@163.com | 签名由网易邮箱大师定制 On 1/20/2021 11:43，苏剑林(Jianlin Su)notifications@github.com wrote： 然后 训练生成的是“extract_model.0.weights” 报错说找不到“extract_model.1.weights” 当我把文件改为“extract_model.1.weights”时， 就报错找不到“extract_model.0.weights”， 很迷惑 | | rmx099128 | | rmx099128@163.com | 签名由网易邮箱大师定制 On 1/20/2021 11:40，rmx099128rmx099128@163.com wrote： 😂， 我这个训练完成了， 这里面又这个文件， 但是它自己就是找不到 不知道什么问题 😓 | | rmx099128 | | rmx099128@163.com | 签名由网易邮箱大师定制 On 1/20/2021 11:39，苏剑林(Jianlin Su)notifications@github.com wrote： 这很明显就是没找到权重文件的意思啊，你是不是没训练完抽取模型？看一下weights目录有没有该文件不就行了？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 训练生成的是extract_model.1.weights～extract_model.14.weights，一共15个文件。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

python extract_model.py 0
python extract_model.py 1
python extract_model.py 2
...
python extract_model.py 14

**Comment by y382957894** [comment]
extract_convert报错：TypeError: Object of type 'int64' is not JSON serializable我也是这个问题不知道该怎么解决。
