### ISSUE TITLE
Valueerror

### ISSUE THREAD

**Issue by renmengxing099128** [bojone/SPACES#9]
Traceback (most recent call last):
  File "extract_model.py", line 183, in <module>
    callbacks=[evaluator]
  File "D:\Anaconda3\envs\python3.6\lib\site-packages\keras\engine\training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "D:\Anaconda3\envs\python3.6\lib\site-packages\keras\engine\training_arrays.py", line 216, in fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "D:\Anaconda3\envs\python3.6\lib\site-packages\keras\callbacks\callbacks.py", line 152, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "extract_model.py", line 149, in on_epoch_end
    metrics = evaluate(valid_data, valid_x, threshold + 0.1)
  File "extract_model.py", line 130, in evaluate
    y_pred = model.predict(data_x)[:, :, 0]
  File "D:\Anaconda3\envs\python3.6\lib\site-packages\keras\engine\training.py", line 1441, in predict
    x, _, _ = self._standardize_user_data(x)
  File "D:\Anaconda3\envs\python3.6\lib\site-packages\keras\engine\training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "D:\Anaconda3\envs\python3.6\lib\site-packages\keras\engine\training_utils.py", line 135, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)

在shell脚本执行过程中出现这个错误， 另外， 权重文件生成时， 只有从（0-4），然后就中断了， 楼主知道什么原因吗？  谢谢~

**Comment by bojone** [comment]
你的语料是不是不够15条？

**Comment by bojone** [comment]
我把示例数据增加到20条了，你可以再试试

**Comment by juanerxiaokeai** [comment]
出现一样的ValueErro问题了，数据有1w多篇，应该不是数据的问题，我还在艰难的查，请问您解决了吗
